config/routes.rb
Rails.application.routes.draw do
  get 'static_pages/home'

  get 'static_pages/help'

  get 'static_pages/about'

  get 'static_pages/contact'

  get 'about' => 'static_pages#about'

  get 'help' => 'static_pages#help'
  get 'contact' => 'static_pages#contact'

  root                 'static_pages#home'

  get   'login' => 'sessions#new'
  post   'login' =>'sessions#create'
  delete  'logout' =>'sessions#destroy'

  get 'signup' => 'users#new'
  resources :users
  post 'projects/:id' =>'projects#add_developer'
  resources :projects do
    resources :stories
  end

end

app/models/project.rb
class Project < ActiveRecord::Base
  has_many :stories, dependent: :destroy
  has_many :users
  validates :title, presence: true, length:{minimum: 5}
end

app/models/story.rb
class Story < ActiveRecord::Base
  belongs_to :project
  has_many :users
end

app/models/user.rb
class User < ActiveRecord::Base
  belongs_to :story
  before_save{self.email=email.downcase}
  validates :name, presence: true
  validates :email, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :logged_in_user, only: [:create,:new, :index,:edit,:update,:show,:destroy]
  #before_action :correct_user, only: [:edit,:update]
  def new
    @project = Project.new
  end
  def create
    @project = Project.new(project_params)
    if @project.save
      redirect_to @project
    else
      render 'new'
    end
  end

  def add_developer
    @project = Project.find(params[:id])
    @user1 = User.find_by(user_params)
    if @user1!=nil && (!@user1.admin?)
      @user1.project_id = @project.id
      @user1.save
      redirect_to @project
    end
  end

  def show
    @user = User.new()
    @project = Project.find(params[:id])
    @point1 = @point2= @point3 = @point4 = @point5 =  0
    @project.stories.each do |s|
      if s.stage == 'Analysis'
        @point1 += s.point.to_f
      end
      if s.stage == 'Read For Dev'
        @point2 += s.point.to_f
      end
      if s.stage == 'In Dev'
        @point3 += s.point.to_f
      end
      if s.stage == 'Dev Complete'
        @point4 += s.point.to_f
      end
      if s.stage == 'In Test'
        @point5 += s.point.to_f
      end
    end
  end

  def edit
    @project = Project.find(params[:id])
  end


  def index
    @projects = Project.all
  end

  def destroy
    @project = Project.find(params[:id])
    @project.destroy
    redirect_to projects_path
  end
  private
  def project_params
     params.require(:project).permit(:title,:description)
  end
  def user_params
    params.require(:user).permit(:email)
  end

  def logged_in_user
    unless logged_in?
      flash[:danger]="Pleasee log in."
      redirect_to login_path
    end
  end

  def correct_user
    @user=User.find(params[:id])
    redirect_to(current_user) unless current_user?(@user)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user=User.find_by(email: params[:session][:email].downcase)
    if user && user.password==params[:session][:password]
      log_in user
      redirect_to user
    else
      flash.now[:danger]='Invalid email/password combination'
      render 'new'
    end
  end

  def destroy
    log_out
    redirect_to root_path
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end

  def about
  end

  def contact
  end
end

app/controllers/stories_controller.rb
class StoriesController < ApplicationController
  def index
    @project = Project.find(params[:project_id])
    @stories = @project.stories.all
  end
  def show
    @project = Project.find(params[:project_id])
    @story = Story.find(params[:id])
    if @story.users.count<2
      current_user.story_id = @story.id
      current_user.save
    end
  end

  def create
    @project = Project.find(params[:project_id])
    @story = @project.stories.create(story_params)
    redirect_to project_path(@project)
  end

  def destroy
    @project = Project.find(params[:project_id])
    @story = @project.stories.find(params[:id])
    @story.destroy
    redirect_to project_path(@project)
  end
  private
    def story_params
      params.require(:story).permit(:title, :description, :point, :stage)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user, only: [:index,:edit,:update,:show,:destroy]
  before_action :correct_user, only: [:edit,:update]

  def index
    @users=User.all
  end

  def new
    @user=User.new
  end

  def create
    @user=User.new(user_params)
    @user.admin=true  if params[:admin]=="true"
    if @user.save
      flash[:success]="Successful created!"
      redirect_to root_path
    else
      render 'new'
    end
  end

  def show
    @user=User.find(params[:id])
  end

  def edit
    @user=User.find(params[:id])
  end

  def update
    @user=User.find(params[:id])
    if @user.update_attributes(user_params)
      flash[:success]="Profile updated!"
      redirect_to @user
    else
      render 'edit'
    end
  end

  def destroy
    User.find(params[:id]).destroy
    flash[:success]="User deleted"
    redirect_to users_url
  end

  private
  def user_params
    params.require(:user).permit(:name, :email, :password, :admin)
  end

  def logged_in_user
    unless logged_in?
      flash[:danger]="Pleasee log in."
      redirect_to login_path
    end
  end

  def correct_user
    @user=User.find(params[:id])
    redirect_to(current_user) unless current_user?(@user)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def full_title(page_title = '')
    base_title = "CSC 517 Project1"
    if page_title.empty?
      base_title
    else
      "#{page_title} | #{base_title}"
    end
  end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def log_in(user)
    session[:user_id]=user.id
  end

  def current_user
    @current_user||=User.find_by(id: session[:user_id])
  end

  def logged_in?
    !current_user.nil?
  end

  def log_out
    session.delete(:user_id)
    @current_user=nil
  end

  def current_user?(user)
    user==current_user
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/stories_helper.rb
module StoriesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
   This is the CSC 517 project 1
  </small>
  <nav>
    <ul>
      <li><%= link_to "About", about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <% if logged_in? %>
      <%= link_to current_user.name, current_user, id: "logo" %>
     <% end %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home", root_path %></li>
        <li><%= link_to "Help", help_path %></li>
        <% if logged_in? %>
          <li><%= link_to "Users", users_path %></li>
          <li><%= link_to "Profile", current_user %></li>
          <li><%= link_to "Settings", edit_user_path(current_user) %></li>
          <li> <%= link_to "Log out", logout_path, method: "delete" %></li>
        <% else %>
          <li><%= link_to "Log in", login_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag 'application', media: 'all',
                                           'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <%= render 'layouts/header' %>
     <div class="container">
    <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
      </div>
    <div class="container">
      <%= yield %>
      <%= render 'layouts/footer'%>
    </div>
  </body>
</html>

app/views/projects/add_developer.html.erb
<h1>add developer</h1>
<% if @user1==nil %>
    <p>the user does not exists!</p>
<% end%>
<% if @user1.admin? %>
    <p>this is an admin!</p>
<% end %>
<%= link_to 'Back', @project%>

app/views/projects/edit.html.erb
<h1>Editing project</h1>

<%= form_for :@project,url: project_path,  method: :patch do |p| %>

    <% if @project.errors.any? %>
        <div id="error_explanation">
          <h2>
            <%= pluralize(@project.errors.count, "error") %> prohibited
            this project from being saved:
          </h2>
          <ul>
            <% @project.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <p>
      <%= p.label :title %><br>
      <%= p.text_field :title %>
    </p>

    <p>
      <%= p.label :description %><br>
      <%= p.text_area :description %>
    </p>

    <p>
      <%= p.submit %>
    </p>

<% end %>

<%= link_to 'Back', projects_path %>

app/views/projects/index.html.erb
<h1>Listing projects</h1>
<% if current_user.admin? %>
<%= link_to 'New Project', new_project_path %>
<% end %>
<table>
  <tr>
    <th>Title</th>
    <th>Description</th>
  </tr>

  <% @projects.each do |p| %>
      <tr>
        <td><%= p.title %></td>
        <td><%= p.description %></td>
        <td><%= link_to 'Show', project_path(p)%></td>
        <% if current_user.admin? %>
            <td><%= link_to 'Destroy', project_path(p), method: :delete,data:{confirm: 'Are you sure?'}%></td>
        <% end %>
      </tr>
  <% end %>

</table>

app/views/projects/new.html.erb
<h1>New Project</h1>
<%= form_for :project, url: projects_path do |p| %>
    <% if @project.errors.any? %>
        <div id="error_explanation">
          <h2>
            <%= pluralize(@project.errors.count, "error") %> prohibited
            this project from being saved:
          </h2>
          <ul>
            <% @project.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
    <% end %>
    <p>
      <%= p.label :title %><br>
      <%= p.text_field :title %>
    </p>

    <p>
      <%= p.label :description %><br>
      <%= p.text_area :description %>
    </p>

    <p>
      <%= p.submit %>
    </p>
<% end %>
<%=link_to 'back', projects_path %>

app/views/projects/show.html.erb
<h1>Show Project</h1>
<p>
  <strong>Title:</strong>
  <%= @project.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @project.description %>
</p>

<p>
  <strong>StoryBoard</strong>
  <p>Analysis <%= @point1%></p>
  <p>Ready For Dev <%= @point2%></p>
  <p>In Dev <%= @point3%></p>
  <p>Dev Complete <%= @point4 %></p>
  <p>In Test <%= @point5 %></p>
</p>

<p>
  <strong>Developer:</strong>
  <%= @project.users.each do |u| %>
    <p>Name:<%= u.name %></p>
    <p>Email:<%= u.email %></p>
  <% end %>
</p>
<%=form_for @user,url: project_path(@project) do |f| %>
    <%= f.label :email%>
    <%= f.email_field :email%>
    <%= f.submit 'add' %>
<% end%>

<p></p>
<%= link_to 'Show Stories',project_stories_path(@project) %>
<%= link_to 'Back', projects_path%>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/static_pages/about.html.erb
<% provide(:title, 'About') %>
<h1>About</h1>
<p> This is about the first project in CSC 517</p>

app/views/static_pages/contact.html.erb
<% provide(:title, 'Contact') %>
<h1>Contact</h1>
<p> Contact us at CSC 517</p>

app/views/static_pages/help.html.erb
<% provide(:title, 'Help') %>
<h1>SOS<br>
If it is an emergency, please call 911
</h1>
<h2>Otherwise,</h2>
<p> Find us at CSC 517</p>

app/views/static_pages/home.html.erb
<div class="center jumbotron">
  <h1>Welcome to the Project1</h1>

  <h2>
    This is the home page for the CSC 517 Project1.
  </h2>

  <%= link_to "Sign up now!", signup_path, class: "btn btn-lg btn-primary" %>
</div>

app/views/stories/_form.html.erb
<%= form_for([@project, @project.stories.build]) do |p| %>
    <p>
      <%= p.label :title %><br>
      <%= p.text_field :title %>
    </p>
    <p>
      <%= p.label :description %><br>
      <%= p.text_area :description %>
    </p>
    <p>
      <%= p.label :point %><br>
      <%= p.text_field :point %>
    </p>
    <p>
      <%= p.label :stage %><br>
      <%= p.select(:stage,[['Analysis', 'Analysis'],['Ready For Dev','Ready For Dev'], ['In Dev', 'In Dev'],['Dev Complete','Dev Complete'],['In Test','In Test'],['Complete','Complete']]) %>
    </p>

    <p>
      <%= p.submit %>
    </p>
<% end %>

app/views/stories/_story.html.erb
<p>
  <strong>Title:</strong>
  <%= story.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= story.description %>
</p>

<p>
  <strong>Point:</strong>
  <%= story.point %>
</p>

<p>
  <strong>Stage:</strong>
  <%= story.stage %>
</p>

<p>
  <strong>Developer:</strong>
      <%= story.users.each do |u| %>
        <p>Name:<%= u.name %></p>
        <p>Email:<%= u.email %></p>
      <% end %>
</p>
<p>
  <% if !current_user.admin? && @project.id == current_user.project_id &&current_user.story_id ==nil %>
  <%= link_to 'Sign Up' , @story %>
  <% end %>
  <% if !current_user.admin? && @project.id == current_user.project_id %>
  <%= link_to 'Destroy Story',[story.project,story],method: :delete, data:{confirm: 'are you sure?'}%>
  <% end%>
</p>
<p>---------------------------</p>

app/views/stories/index.html.erb
<h1>Listing stories</h1>
<h2>Stories</h2>
<% @stories.each do |story| %>
    <p>
      <strong>Title:</strong>
      <%= story.title %>
    </p>

    <p>
      <strong>Description:</strong>
      <%= story.description %>
    </p>

    <p>
      <strong>Point:</strong>
      <%= story.point %>
    </p>

    <p>
      <strong>Stage:</strong>
      <%= story.stage %>
    </p>

    <p>
      <strong>Developer:</strong>
      <%= story.users.each do |u| %>
        <p>Name:<%= u.name %></p>
        <p>Email:<%= u.email %></p>
    <% end %>
    </p>
    <p>
      <% if !current_user.admin? && @project.id == current_user.project_id &&current_user.story_id ==nil %>
          <%= link_to 'Sign up', project_story_path(@project, story)%>
      <% end %>

      <% if !current_user.admin? && @project.id == current_user.project_id %>
          <%= link_to 'Destroy Story',[story.project,story],method: :delete, data:{confirm: 'are you sure?'}%>
      <% end%>
    </p>
    <p>---------------------------</p>
<% end %>
<% if !current_user.admin? && @project.id == current_user.project_id %>
<%= render 'form' %>
<% end %>
<%= link_to 'Back', @project%>

app/views/stories/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @story.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @story.description %>
</p>

<p>
  <strong>Point:</strong>
  <%= @story.point %>
</p>

<p>
  <strong>Stage:</strong>
  <%= @story.stage %>
</p>
<p>
  <strong>Developer:</strong>
  <%= @story.users.each do |u| %>
    <p>Name:<%= u.name %></p>
    <p>Email:<%= u.email %></p>
<% end %>
</p>
<p>
  <%= link_to 'Back', @stories%>
</p>

app/views/users/_user.html.erb
<p>
  <strong>name</strong>
  <%= user.name %>
</p>

app/views/users/edit.html.erb
<% provide(:title, "Edit user") %>
<h1>Update your profile</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages' %>

      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>

      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %>

      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.submit "Save changes", class: "btn btn-primary" %>
    <% end %>

  </div>
</div>

app/views/users/index.html.erb
<% provide(:title, 'All users') %>
<h1>All users</h1>

<ul class="users">
  <% @users.each do |user| %>
    <li>
      <%= link_to user.name, user %>
      <%if current_user.admin? && !current_user?(user)%>
      | <%= link_to "delete", user, method: :delete,data: {confirm: "You sure?"}%>
      <%end%>
      
     
    </li>
  <% end %>
</ul>

app/views/users/new.html.erb
<h1>Sign up</h1>

<%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages' %>

      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>

      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %>

      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>
      
      <%= radio_button_tag(:admin, false) %>
      <%= label_tag(:role_developer, "Developer") %>
      <%= radio_button_tag(:admin, true) %>
      <%= label_tag(:role_admin, "Admin") %>
     <br>

      <%= f.submit "Create account",class: "btn btn-primary"  %>
    <% end %>

app/views/users/show.html.erb
<% provide(:title, 'Profile') %>
<h1>User Profile</h1>
<p>
  <b>Name:</b><br>
  <%= @user.name %><br>
  <b>Email:</b><br>
  <%= @user.email %><br>
  <b>Role:</b><br>
  <% if@user.admin %>
      Administer
  <%else%>
      Developer
  <%end%>
</p>
<%= link_to "show all projects", projects_path %>
<% if current_user.admin? && current_user?(@user)%>
    <div><%= link_to "add people", signup_path %></div>


<%end%>

app/views/welcome/index.html.erb
<h1>Welcome#index</h1>
<p>Find me in app/views/welcome/index.html.erb</p>
<%= link_to 'my project', controller: 'projects'%>